# Render.com configuration for React + Vite SPA
# Ensures correct build and start commands for static hosting

# Render.com configuration for Vite/React static site
# Ensures correct build and publish commands for static hosting

services:
  - type: web
    name: testimonial-heym
    env: node
    plan: free # Ensure you're on the free plan
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist
    envVars:
      - key: NODE_VERSION
        value: 20 # Specify a recent Node.js version
