# Render.com configuration for React + Vite SPA
# Ensures correct build and start commands for static hosting

# Render.com configuration for Vite/React static site
# Ensures correct build and publish commands for static hosting

services:
  - type: static
    name: testimonial-heym
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    rewrites:
      - source: /*
        destination: /index.html
