// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use Vite env variables for configuration
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined;

if (!SUPABASE_URL?.startsWith('http')) {
	throw new Error('Supabase URL is missing or invalid. Set VITE_SUPABASE_URL in your .env');
}

if (!SUPABASE_PUBLISHABLE_KEY) {
	throw new Error('Supabase anon key is missing. Set VITE_SUPABASE_ANON_KEY in your .env');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);