// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgmomsidhbjcmmgtnkyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtnbW9tc2lkaGJqY21tZ3Rua3lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1ODM3NjAsImV4cCI6MjA2NjE1OTc2MH0.oWV0cJ75OsYsPxz_2WBIfrTOFCNaSRD0aNClOnZO1a0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);